identifier: kald6clfld30bf78
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: kinderkulturUx
homeFolder: /Users/administrator/Documents/scm/petruschka/petruschka-serverless
distFolder: ./dist/kinderkulturUx
outDir: >-
  /Users/administrator/Documents/scm/petruschka/petruschka-serverless/dist/static
handle404: ''
