identifier: kald6clfld30bf78
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: kinderkulturUx
homeFolder: /Users/linuswieland/Documents/scm/petruschka-ch
distFolder: ./dist/kinderkulturUx
outDir: /Users/linuswieland/Documents/scm/petruschka-ch/dist/static
handle404: ''
