identifier: kald6clfld30bf78
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: kinderkulturUx
homeFolder: /Users/linus/Documents/scm/petruschka/PetruschkaUx
distFolder: ./dist/kinderkulturUx
outDir: /Users/linus/Documents/scm/petruschka/PetruschkaUx/dist/static
handle404: ''
